-- MySQL Script generated by MySQL Workbench
-- Sun May  1 18:49:03 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema rms
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rms` DEFAULT CHARACTER SET utf8 ;
USE `rms` ;

-- -----------------------------------------------------
-- Table `rms`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rms`.`admin` (
  `a_id` INT NOT NULL AUTO_INCREMENT,
  `a_name` VARCHAR(20) NULL,
  `a_password` VARCHAR(20) NULL,
  `a_phone` VARCHAR(15) NULL,
  `a_email` VARCHAR(25) NULL,
  `a_permission` INT NULL,
  `a_del` TINYINT(1) NULL,
  PRIMARY KEY (`a_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rms`.`food_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rms`.`food_type` (
  `ft_id` INT NOT NULL AUTO_INCREMENT,
  `ft_name` VARCHAR(45) NULL,
  `ft_del` TINYINT(1) NULL,
  PRIMARY KEY (`ft_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rms`.`food`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rms`.`food` (
  `f_id` INT NOT NULL AUTO_INCREMENT,
  `f_name` VARCHAR(10) NULL,
  `f_img` VARCHAR(45) NULL,
  `f_uptime` DATETIME NULL,
  `f_del` TINYINT(1) NULL,
  `f_admin_id` INT NOT NULL,
  `f_food_type_id` INT NOT NULL,
  PRIMARY KEY (`f_id`),
  INDEX `fk_food_admin1_idx` (`f_admin_id` ASC),
  INDEX `fk_food_food_type1_idx` (`f_food_type_id` ASC),
  CONSTRAINT `fk_food_admin1`
    FOREIGN KEY (`f_admin_id`)
    REFERENCES `rms`.`admin` (`a_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_food_food_type1`
    FOREIGN KEY (`f_food_type_id`)
    REFERENCES `rms`.`food_type` (`ft_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rms`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rms`.`user` (
  `u_id` INT NOT NULL AUTO_INCREMENT,
  `u_name` VARCHAR(45) NULL,
  `u_password` VARCHAR(45) NULL,
  `u_phone` VARCHAR(45) NULL,
  `u_city` VARCHAR(20) NULL,
  `u_img` VARCHAR(45) NULL,
  `u_sex` VARCHAR(5) NULL,
  `u_uptime` DATETIME NULL,
  `u_score` INT NULL,
  `u_del` TINYINT(1) NULL,
  PRIMARY KEY (`u_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rms`.`seat_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rms`.`seat_status` (
  `ss_id` INT NOT NULL AUTO_INCREMENT,
  `ss_name` VARCHAR(45) NULL,
  `ss_del` TINYINT(1) NULL,
  PRIMARY KEY (`ss_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rms`.`seat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rms`.`seat` (
  `st_id` INT NOT NULL AUTO_INCREMENT,
  `st_name` VARCHAR(20) NULL,
  `st_limit` INT NULL,
  `st_del` TINYINT(1) NULL,
  `st_seat_status_id` INT NOT NULL,
  `st_admin_id` INT NOT NULL,
  PRIMARY KEY (`st_id`),
  INDEX `fk_seat_seat_status1_idx` (`st_seat_status_id` ASC),
  INDEX `fk_seat_admin1_idx` (`st_admin_id` ASC),
  CONSTRAINT `fk_seat_seat_status1`
    FOREIGN KEY (`st_seat_status_id`)
    REFERENCES `rms`.`seat_status` (`ss_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seat_admin1`
    FOREIGN KEY (`st_admin_id`)
    REFERENCES `rms`.`admin` (`a_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rms`.`coupon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rms`.`coupon` (
  `c_id` INT NOT NULL AUTO_INCREMENT,
  `c_discount` DECIMAL(2) NULL,
  `c_name` VARCHAR(45) NULL,
  `c_detail` VARCHAR(200) NULL,
  `c_code` VARCHAR(45) NULL,
  `c_begin_time` DATE NULL,
  `c_end_time` DATE NULL,
  `c_limit` INT NULL,
  `c_del` TINYINT(1) NULL,
  `c_admin_id` INT NOT NULL,
  PRIMARY KEY (`c_id`),
  INDEX `fk_coupon_admin1_idx` (`c_admin_id` ASC),
  CONSTRAINT `fk_coupon_admin1`
    FOREIGN KEY (`c_admin_id`)
    REFERENCES `rms`.`admin` (`a_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rms`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rms`.`order` (
  `o_id` INT NOT NULL AUTO_INCREMENT,
  `o_uptime` DATETIME NULL,
  `o_origin_price` DECIMAL(2) NULL,
  `o_discount` DECIMAL(1) NULL,
  `o_pay_price` DECIMAL(2) NULL,
  `o_paid` TINYINT(1) NULL,
  `o_evaluate` INT NULL,
  `o_notes` VARCHAR(100) NULL,
  `o_handler` VARCHAR(10) NULL,
  `o_score` INT NULL,
  `o_seat_id` INT NOT NULL,
  `o_admin_id` INT NOT NULL,
  `o_user_id` INT NOT NULL,
  `o_coupon_id` INT NOT NULL,
  PRIMARY KEY (`o_id`),
  INDEX `fk_order_seat1_idx` (`o_seat_id` ASC),
  INDEX `fk_order_admin1_idx` (`o_admin_id` ASC),
  INDEX `fk_order_user1_idx` (`o_user_id` ASC),
  INDEX `fk_order_coupon1_idx` (`o_coupon_id` ASC),
  CONSTRAINT `fk_order_seat1`
    FOREIGN KEY (`o_seat_id`)
    REFERENCES `rms`.`seat` (`st_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_admin1`
    FOREIGN KEY (`o_admin_id`)
    REFERENCES `rms`.`admin` (`a_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_user1`
    FOREIGN KEY (`o_user_id`)
    REFERENCES `rms`.`user` (`u_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_coupon1`
    FOREIGN KEY (`o_coupon_id`)
    REFERENCES `rms`.`coupon` (`c_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rms`.`purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rms`.`purchase` (
  `p_id` INT NOT NULL AUTO_INCREMENT,
  `p_uptime` DATETIME NULL,
  `p_payment` DECIMAL(2) NULL,
  `p_handler` VARCHAR(10) NULL,
  `p_detail` VARCHAR(1000) NULL,
  `p_admin_id` INT NOT NULL,
  PRIMARY KEY (`p_id`),
  INDEX `fk_purchase_admin1_idx` (`p_admin_id` ASC),
  CONSTRAINT `fk_purchase_admin1`
    FOREIGN KEY (`p_admin_id`)
    REFERENCES `rms`.`admin` (`a_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rms`.`news_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rms`.`news_type` (
  `nt_id` INT NOT NULL AUTO_INCREMENT,
  `nt_name` VARCHAR(45) NULL,
  `nt_del` TINYINT(1) NULL,
  PRIMARY KEY (`nt_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rms`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rms`.`news` (
  `n_id` INT NOT NULL AUTO_INCREMENT,
  `n_title` VARCHAR(45) NULL,
  `n_uptime` DATETIME NULL,
  `n_img` VARCHAR(45) NULL,
  `n_intro` VARCHAR(50) NULL,
  `n_detail` VARCHAR(2000) NULL,
  `n_del` TINYINT(1) NULL,
  `n_admin_id` INT NOT NULL,
  `n_news_type_id` INT NOT NULL,
  `coupon_c_id` INT NOT NULL,
  PRIMARY KEY (`n_id`),
  INDEX `fk_news_admin1_idx` (`n_admin_id` ASC),
  INDEX `fk_news_news_type1_idx` (`n_news_type_id` ASC),
  INDEX `fk_news_coupon1_idx` (`coupon_c_id` ASC),
  CONSTRAINT `fk_news_admin1`
    FOREIGN KEY (`n_admin_id`)
    REFERENCES `rms`.`admin` (`a_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_news_news_type1`
    FOREIGN KEY (`n_news_type_id`)
    REFERENCES `rms`.`news_type` (`nt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_news_coupon1`
    FOREIGN KEY (`coupon_c_id`)
    REFERENCES `rms`.`coupon` (`c_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rms`.`evaluate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rms`.`evaluate` (
  `e_id` INT NOT NULL AUTO_INCREMENT,
  `e_uptime` DATETIME NULL,
  `e_content` VARCHAR(100) NULL,
  `e_del` TINYINT(1) NULL,
  `e_news_id` INT NOT NULL,
  `e_user_id` INT NOT NULL,
  PRIMARY KEY (`e_id`),
  INDEX `fk_evaluate_news1_idx` (`e_news_id` ASC),
  INDEX `fk_evaluate_user1_idx` (`e_user_id` ASC),
  CONSTRAINT `fk_evaluate_news1`
    FOREIGN KEY (`e_news_id`)
    REFERENCES `rms`.`news` (`n_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evaluate_user1`
    FOREIGN KEY (`e_user_id`)
    REFERENCES `rms`.`user` (`u_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rms`.`rule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rms`.`rule` (
  `r_id` INT NOT NULL AUTO_INCREMENT,
  `r_score` INT NULL,
  `r_discount` DECIMAL(2) NULL,
  `r_name` VARCHAR(45) NULL,
  `r_del` TINYINT(1) NULL,
  `r_admin_id` INT NOT NULL,
  PRIMARY KEY (`r_id`),
  INDEX `fk_rule_admin1_idx` (`r_admin_id` ASC),
  CONSTRAINT `fk_rule_admin1`
    FOREIGN KEY (`r_admin_id`)
    REFERENCES `rms`.`admin` (`a_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rms`.`sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rms`.`sale` (
  `sl_id` INT NOT NULL AUTO_INCREMENT,
  `sl_date` DATE NULL,
  `sl_total` INT NULL,
  `sl_leave` INT NULL,
  `sl_food_id` INT NOT NULL,
  PRIMARY KEY (`sl_id`),
  INDEX `fk_sale_food1_idx` (`sl_food_id` ASC),
  CONSTRAINT `fk_sale_food1`
    FOREIGN KEY (`sl_food_id`)
    REFERENCES `rms`.`food` (`f_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
